config/routes.rb
Rails.application.routes.draw do
  resources :groupreviews
  resources :users
  resources :groups do
    resources :movies
    resources :users
  end
  resources :reviews


  root to: "groupreviews#index"

  # post 'invite' to: 'user#invite'
  get 'login', to: 'session#new'
  post 'login', to: 'session#create'
  delete 'logout', to: 'session#destroy'
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :reviewers
  has_many :users, through: :reviewers
  has_many :group_reviews
  has_many :movies, through: :group_reviews

  validates :group_name, { presence: true }
end

app/models/group_review.rb
class GroupReview < ActiveRecord::Base
  belongs_to :group
  belongs_to :movie
  has_many :reviews

  validates :due_date, { presence: true }
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  has_many :group_reviews

  validates :title, :body, :poster_image, { presence: true }

  accepts_nested_attributes_for :group_reviews
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :group_review

end

app/models/reviewer.rb
class Reviewer < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reviewers
  has_many :groups, through: :reviewers
  has_many :reviews

  has_secure_password(validations: false)
  validates :email, presence: true, length:{minimum: 5}

  def add_token
    self.token = SecureRandom.hex(12)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/groupreviews_controller.rb
class GroupreviewsController < ApplicationController
  def index
    @groupreviews = GroupReview.all
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  include ApplicationHelper

  before_filter :admin_authenticate

  def new
    @group = Group.new
    @groups = Group.all
    render :new
  end

  def create
    @group = Group.new(user_params)
    puts params
    if @group.save
      redirect_to new_group_movie_path(@group.id)
    else
      flash[:empty] = "Field cannot be empty!"
      redirect_to new_group_path
    end
  end

  def show
    @group = Group.find(params[:id])
    @due_date = @group.group_reviews[0].due_date
    @movie = @group.movies[0]
  end

  private
  def user_params
    params.require(:group).permit(:group_name)
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  include ApplicationHelper
  before_filter :admin_authenticate

  def new
    admin_authenticate
    @group = Group.find(params[:group_id])
    @greview = GroupReview.new
    @movie = Movie.new
    render :new
  end

  #this is for when mike creates a new user with just an email
  def create
    admin_authenticate
    @movie = Movie.new(movie_params)
    @group = Group.find(params[:group_id])
     if @movie.save
       p params[:due_date]
       review = GroupReview.create(group_id: @group.id, movie_id: @movie.id, due_date: params[:movie][:group_review][:due_date])
       redirect_to new_group_user_path(@group.id)
    else
      flash[:empty] = "Field(s) cannot be empty!"
      redirect_to new_group_movie_path
    end
  end

  private
  def movie_params
    params.require(:movie).permit(:title, :body, :poster_image)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  include ApplicationHelper

  before_filter :authenticate!, except: [:index, :show] 

  def index
    @reviews = Review.all
  end

  def show
    @user = User.find(session[:user_id])
    @review = Review.find(params[:id])
    render :show
  end

  def create
    @review = Review.find(params[:id])
    render :show
  end

  def edit
    @review = Review.find(params[:id])
    render :edit
  end

  def update
    @review = Review.find(params[:id])

    if @review.update(params[:review].permit(:title, :body))
      redirect_to @review
    else
      render :edit
    end
  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def new
  end

  def create
    @user= User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to @user
    else
      flash[:danger]= ':invalid username or password.'
      render 'new'
    end
  end

  def destroy
    session.clear
    @current_user = nil
    flash[:success] = 'You are logged out.'
    redirect_to login_path
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.add_token
     if @user.save
       UserMailer.invite_email(@user).deliver_later
       redirect_to root_path
    else
      render :new
    end
  end

  def set_password
    @user.find_by(email: params[:email])
    if params[:token] == @user.token
      @user.password = params[:password]
      @user.save
      redirect_to login_path
    else
      redirect_to root_path
    end
  end

  private
  def user_params
    params.require(:user).permit(:email)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @group = Group.find(params[:group_id])
    @user = User.new
    render :new
  end

  #this is for when mike creates a new user with just an email
  def create
    @user = User.new(user_params)
    @user.add_token
    @tempass = SecureRandom.hex(4)
    @user.password = @tempass
    @group = Group.find(params[:group_id])
    if @user.save
      @reviewer = Reviewer.create(user_id: @user.id, group_id: @group.id)
      @groupreview = GroupReview.find_by(group_id: @group.id)
      Review.create(title: "", body: "", user_id: @user.id, group_review_id: @groupreview.id )
      UserMailer.invite_mailer(@user, @tempass).deliver
      redirect_to '/'
    else
      flash[:empty] = "Field cannot be empty!"
      redirect_to new_group_user_path
    end
  end

  def show
    @user = User.find(params[:id])
    @reviews = @user.reviews
    puts "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
    puts @reviews
  end

  def set_password
    @user.find_by(email: params[:email])
    if params[:token] == @user.token
      @user.password = params[:password]
      @user.save
      redirect_to login_path
    else
      redirect_to root_path
    end
  end

  private
  def user_params
    params.require(:user).permit(:email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def time_since(time)
    hours = ((Time.now - time) / 3600).round
    minutes = ((Time.now - time) / 60).round

    return "#{(hours / 24).round} day(s) ago" if hours > 24

    if minutes < 1
      return "#{(minutes * 60).round} seconds ago"
    elsif minutes >= 60
      return "#{hours} hour(s) ago"
    else
      return "#{minutes} minute(s) ago"
    end
  end

  def review_completed?(review)
    review.group_review.due_date.past?
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def admin_authenticate
    @admin = User.find(1)
    if session[:user_id] != @admin.id
      redirect_to '/'
    end
  end


def authenticate!
  redirect_to '/' unless session[:user_id]
end

end

app/helpers/groupreviews_helper.rb
module GroupreviewsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/session_helper.rb
module SessionHelper
  def current_user
    @current_user ||= User.find(session[:user_id])
  end

  def logged_in?
    session[:user_id] != nil
  end

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/groupreviews/index.html.erb
<div id="main-card">
<% @groupreviews.order('due_date DESC').each do |groupreview| %>
<a href="/groupreviews/<%=groupreview.id%>">
    <div class="movie-cards">
    <img id="movie-poster-cards" src=<%= groupreview.movie.poster_image %>>

    <div id="group-name">Reviewed by: <%= groupreview.group.group_name %></h3></div>
    </div>

</a>
  <%end %>
</ul>
</div>

app/views/groupreviews/show.html.erb
<div id="whole-grouppage-reviews">

  <div id="movie-info">
    <h2 id="movietitle"><%= @groupreview.movie.title %></h2> <br>
     <p id="reviewbody"> Directed by <%= @groupreview.movie.body %> </p>
  </div>
  <img class = "movie-poster"  src= <%= @groupreview.movie.poster_image %> >
    <% @groupreview.reviews.each do |review| %>

    <div class="reviews">
      <h2 id="review-title" ><%= review.title %></h2>
      <p id="review-body"> <%= review.body %>
        <br>
          <span> <%=review.user.email%></span>
  </div>
      </p>

    <%end%>

</div>

app/views/groups/new.html.erb
<div id="whole-grouppage">

  <h1 id="start-group">Start a new group</h1>

<% if flash.any? %>
  <% flash.each do |message_type, message| %>
    <p id="flash-message"><%=message%></p>
  <% end %>
<% end %>

  <div id="form">
    <%= form_for @group do |f| %>
      <%= f.text_field :group_name, placeholder: "Group Name" %><br>
      <%= f.submit "MIKES IT!"%>
    <% end %>
  </div>


  <h4 id="current">Invite friends to existing groups</h4>
  <% @groups.each do |group| %>
  <ul id="grouplist">
    <li id="groups">
      <%= link_to group.group_name, new_group_user_path(group.id) %>
    </li>
  </ul>
  <% end %>
</div>

app/views/groups/show.html.erb
<div id="whole-grouppage">

<div class=show>
  <h2 id="edit"> Your group is reviewing: </h2>

  <br>

  <h1 id="movie-title"> <%= @movie.title %> </h1>
  <img src="<%= @movie.poster_image %>" width=250 height="350">

  <br>
  <h4 id="duedate-header"> Reviews are due by: <%= @due_date.strftime("%B %d, %Y") %> </h4>

</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset='utf-8'>
<link href='https://fonts.googleapis.com/css?family=Quicksand' rel='stylesheet' type='text/css'>
  <title>MovieApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
    <div id="header">
      <a id="logo" href ="/"><%= image_tag("mikelikes.png")%></a>
    </div>

  <nav>
    <% if logged_in? %>
      <%= link_to 'logout', logout_path, method: :delete%>
      <%= link_to current_user.email, user_path(current_user) %>
        <% if current_user.id == 1 %>
            <a href = "/groups/new">mike a group</a>
        <% end %>
    <% else %>
      <a href="/login">login</login></a>
    <% end %>
  </nav>


<%= yield %>

</body>
</html>

app/views/movies/new.html.erb
<div id="whole-grouppage">

<h1 id="edit"> Mike, pick a movie for <%= @group.group_name %> to review.</h2>

<% if flash.any? %>
  <% flash.each do |message_type, message| %>
    <p id="flash-message"><%=message%></p>
  <% end %>
<% end %>

<%= form_for [@group, @movie] do |f| %>

  <%= f.text_field :title, placeholder: "Title" %><br><br>

  <%= f.text_field :body, placeholder: "Description" %><br><br>

  <%= f.text_field :poster_image, placeholder: "Image URL"  %><br><br>

  <%= f.fields_for @greview do |gr| %>

    <%= gr.text_field :due_date, placeholder: "Due Date" %><br><br>
  <% end %>

  <%= f.submit("Mike <3 movies") %>
<% end %>
</div>

app/views/reviews/edit.html.erb
<div id ="whole-grouppage">
  <h1 id="edit"> Edit your shit here </h1>

  <%= form_for @review do |f| %>
    <%= f.text_field :title%>
    <br>
    <br>
    <%= f.text_area :body, size: "50x15"%>
    <br>
    <br>
    <%= f.submit %>
  <% end %>
</div>

app/views/reviews/show.html.erb
<div id ="whole-grouppage">
  <h1 id="title"> <%= @review.group_review.movie.title %>
    <% if @review.title.length > 1 && @review.body.length > 1%>

      <% if !review_completed?(@review) %>
        <h2 id="edit-title"><%= link_to "Edit this review", "/reviews/#{@review.id}/edit" %></h2>
      <% else %>
        <h2 id="edit-title">This review is already published and cannot be edited </h2>
      <% end %>

  <h3 id="review-title"><%= @review.title %></h3>
  <br>
  <p id="review-body"><%= @review.body %></p>


    <% else %>

      <% if !review_completed?(@review) %>
        <h2 id="edit"> Looks like you haven't done this review yet, better do it soon so you dont dissapoint Mike. </h2>

          <%= form_for @review do |f| %>
                <%= f.text_field :title, placeholder: "Title"%>
                <br>
                <br>

            <%= f.text_area :body, placeholder: "Content", size: "50x15" %>
            <br>
            <br>
            <%= f.submit %>
          <% end %>
      <% else %>
         <h2 id="edit">You missed the due date and now Mike is mad at you. </h2>
      <% end %>
    <% end %>
</div>

app/views/session/new.html.erb
<div id="whole-grouppage">
  <h1 id="login"> Login</h1>

    <%= form_tag login_path do %>


      <% if flash.any? %>
        <% flash.each do |message_type, message| %>
          <p id="flash-message"><%=message%></p>
        <% end %>
      <% end %>
  <br>




  <%= text_field_tag :email, params[:email], placeholder: "Email" %>
  <br>
  <br>

  <%= password_field_tag :password, params[:password], placeholder: "Password"%>
  <br>
  <br>

  <%= submit_tag "Go" %>
<% end %>

app/views/users/new.html.erb
<div id="whole-grouppage">
  <h1 id="welcome-mike"> Hey Mike.<br> Invite some people to <%= @group.group_name %>. </h1>

<% if flash.any? %>
  <% flash.each do |message_type, message| %>
    <p id="flash-message"><%=message%></p>
  <% end %>
<% end %>

<%= form_for [@group, @user] do |f| %>
  <%= f.text_field :email, placeholder: "Enter their email" %> <br>
  <%= f.submit("Invite!") %>
<% end %>
</div>

app/views/users/show.html.erb
<div id="whole-page">

<div id="to-complete">
  <h2> Reviews to complete: </h2>
  <p>
    <% @reviews.each do |review| %>
      <% if !review_completed?(review) %>
        <% if review.title.length > 1 && review.body.length > 1%>
            <h4> <%= link_to review.group_review.movie.title, "/reviews/#{review.id}" %> </h4>
        <% else %>
          <%= link_to "Create a new review for " + review.group_review.movie.title, "/reviews/#{review.id}" %>
        <% end %>
      <% end %>
    <% end %>
  </p>
</div>

<div id="have-completed">
  <h2> Reviews completed: </h2>
  <% @reviews.each do |review| %>
    <% if review_completed?(review) %>
  <p class="review-info">
    <h4> <%= link_to review.title, "/reviews/#{review.id}" %> </h4>
  </p>
    <% end %>
  <% end %>
</div>

<div id="group-membership">
  <h2> Your groups: </h2>
<p>
  <% @user.groups.each do |group| %>
    <h4> <%= link_to group.group_name, group_path(group.id) %> </h4>
  <% end %>
</p>
</div>
</div>